# Generated by Django 5.1.7 on 2025-06-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('jobpostings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.candidate'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobposting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostings.jobposting'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('jobposting', 'candidate'), name='unique_active_job_application'),
        ),
    ]
