# Generated by Django 5.1.7 on 2025-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_initial"),
        ("jobpostings", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("jobposting", "candidate"), name="unique_active_job_application"
            ),
        ),
    ]
