# Generated by Django 5.1.7 on 2025-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_jobapplication_unique_active_job_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
