# Generated by Django 5.1.7 on 2025-06-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpostings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter'),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_skills', to='jobpostings.jobposting'),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_postings', to='jobpostings.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='jobpostingskill',
            unique_together={('job_posting', 'skill')},
        ),
    ]
