# Generated by Django 5.1.7 on 2025-03-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobpostings", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.recruiter"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="required_skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
    ]
